{% set name = "elmfire" %}
{% set version = "2025.0131" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lautenberger/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: da4de3082591dd36bd9d0c7c80388307366447454b7546acbdc8932d5ae29f6a

build:
  number: 0
  skip: true  # [win]
  script_env:
    - ELMFIRE_VERSION={{ version }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - sed
  host:
    - openmpi
  run:
    - openmpi

test:
  commands:
    - test -f $PREFIX/bin/elmfire

about:
  home: https://elmfire.io/
  license: EPL-2.0
  license_file: LICENSE.md
  summary: Eulerian Level set Model of FIRE Spread
  description: ELMFIRE is an operational wildland fire spread model. Some of its common applications include; Forecasting spread of fires in real time, Reconstructing spread of historical fires, Quantifying landscape-scale potential fire behavior potential, and Estimating annual burn probability and fire severity.
  doc_url: https://elmfire.io/user_guide.html
  dev_url: https://github.com/lautenberger/elmfire

extra:
  recipe-maintainers:
    - lautenberger
    - mccarthyryanc
