{% set name = "elmfire" %}
{% set version = "2025.0526" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lautenberger/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6f043180124ee574cc586c6ae89d43292500730bff4f9f30820fba9b0da21590

build:
  number: 0
  skip: true  # [not linux]
  script_env:
    - ELMFIRE_VERSION={{ version }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - sed
  host:
    - openmpi
  run:
    - openmpi
    - _openmp_mutex  # [linux]

test:
  commands:
    - test -f $PREFIX/bin/elmfire
    - test -f $PREFIX/bin/elmfire_debug
    - test -f $PREFIX/bin/elmfire_post
    - test -f $PREFIX/bin/elmfire_post_debug

about:
  home: https://elmfire.io/
  license: EPL-2.0
  license_file: LICENSE.md
  summary: Eulerian Level set Model of FIRE Spread
  description: ELMFIRE is an operational wildland fire spread model. Some of its common applications include; Forecasting spread of fires in real time, Reconstructing spread of historical fires, Quantifying landscape-scale potential fire behavior potential, and Estimating annual burn probability and fire severity.
  doc_url: https://elmfire.io/user_guide.html
  dev_url: https://github.com/lautenberger/elmfire

extra:
  recipe-maintainers:
    - lautenberger
    - mccarthyryanc
